part of 'app_localizations.dart';

Map<String, Map<String, String>> _text = {
  'en': {
    'title': 'App Title',
    'new_challenge_button': 'New Challenge',
    'current_streak': 'Current streak',
    'longest_streak': 'Longest streak',
    'year_singular': 'year',
    'year_plural': 'years',
    'day_singular': 'day',
    'day_plural': 'days',
    'and': 'and',
    'thats_okay': 'That’s okay',
    'you_are_awesome': 'You’re still awesome!',
    'im_awesome': 'I’M AWESOME',
    'facebook_login_button': 'LOG IN WITH FACEBOOK',
    'login_button': 'LOG IN',
    'sign_up_button': 'SIGN UP',
    'forgot_password': 'Forgot Password?',
    // Challenges
    'beef_long': 'Avoid eating beef',
    'beef_medium': 'Avoid beef',
    'beef_short': 'Beef',
    'beef_encouragement': 'I hope you enjoyed the beef.',
    'beef_description': 'Did you know that beef’s environmental impact dwarfs that of other meat including chicken and pork, new research reveals, with one expert saying that eating less red meat would be a better way for people to cut carbon emissions than giving up their cars.',
    'flying_long': 'Avoid flying',
    'flying_medium': 'Avoid flying',
    'flying_short': 'Flying',
    'flying_encouragement': 'Enjoy your flight.',
    'flying_description': 'Mauris fringilla enim a volutpat gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque quis ex eu mi sollicitudin rhoncus. Proin eu commodo ex, vitae lobortis tellus. Nunc vitae venenatis nulla. Mauris in tellus non nulla pharetra molestie ac ut magna.',
  },
  'da': {
    'title': 'App Titel',
    'new_challenge_button': 'Ny Udfordring',
    'current_streak': 'Nuværende streak',
    'longest_streak': 'Længste streak',
    'year_singular': 'år',
    'year_plural': 'år',
    'day_singular': 'dag',
    'day_plural': 'dage',
    'and': 'og',
    'thats_okay': 'Det er okay',
    'you_are_awesome': 'Du er stadig nice!',
    'im_awesome': 'JEG ER NICE',
    'facebook_login_button': 'LOG IND MED FACEBOOK',
    'login_button': 'LOG IND',
    'sign_up_button': 'REGISTRER',
    'forgot_password': 'Glemt Adgangskode?',
    // Challenges
    'beef_long': 'Undgå at spise oksekød',
    'beef_medium': 'Undgå oksekød',
    'beef_short': 'Oksekød',
    'beef_encouragement': 'Jeg håber, det smagte godt.',
    'beef_description': 'Aliquam luctus vulputate dui eget laoreet. Ut imperdiet nisl vel tellus feugiat, quis gravida magna pellentesque. Vestibulum fermentum nunc eu nisl maximus, non sollicitudin mauris lobortis. Maecenas id gravida massa, at cursus felis. Vestibulum condimentum, nibh eu pulvinar fermentum, magna odio pretium ligula, sit amet pharetra nunc mauris vel ante.',
    'flying_long': 'Undgå at flyve',
    'flying_medium': 'Undgå at flyve',
    'flying_short': 'Flyve',
    'flying_encouragement': 'Hav en god flyvetur.',
    'flying_description': 'Mauris fringilla enim a volutpat gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque quis ex eu mi sollicitudin rhoncus. Proin eu commodo ex, vitae lobortis tellus. Nunc vitae venenatis nulla. Mauris in tellus non nulla pharetra molestie ac ut magna.',
  },
};