part of 'app_localizations.dart';

Map<String, Map<String, String>> _text = {
  'en': {
    'title': 'App Title',
    'new_challenge_button': 'New Challenge',
    'current_streak': 'Current streak',
    'longest_streak': 'Longest streak',
    'year_singular': 'year',
    'year_plural': 'years',
    'day_singular': 'day',
    'day_plural': 'days',
    'and': 'and',
    'thats_okay': 'That’s okay',
    'you_are_awesome': 'You’re still awesome!',
    'im_awesome': 'I’M AWESOME',
    // Challenges
    'challenge_beef_long': 'Avoid eating beef',
    'challenge_beef_medium': 'Avoid beef',
    'challenge_beef_short': 'Beef',
    'beef_encouragement': 'I hope you enjoyed the beef.',
    'challenge_flying_long': 'Avoid flying',
    'challenge_flying_medium': 'Avoid flying',
    'challenge_flying_short': 'Flying',
    'flying_encouragement': 'Enjoy your flight.',
  },
  'da': {
    'title': 'App Titel',
    'new_challenge_button': 'Ny Udfordring',
    'current_streak': 'Nuværende streak',
    'longest_streak': 'Længste streak',
    'year_singular': 'år',
    'year_plural': 'år',
    'day_singular': 'dag',
    'day_plural': 'dage',
    'and': 'og',
    'thats_okay': 'Det er okay',
    'you_are_awesome': 'Du er stadig nice!',
    'im_awesome': 'JEG ER NICE',
    // Challenges
    'challenge_beef_long': 'Undgå at spise oksekød',
    'challenge_beef_medium': 'Undgå oksekød',
    'challenge_beef_short': 'Oksekød',
    'beef_encouragement': 'Jeg håber det smagte godt.',
    'challenge_flying_long': 'Undgå at flyve',
    'challenge_flying_medium': 'Undgå at flyve',
    'challenge_flying_short': 'Flyve',
    'flying_encouragement': 'Hav en god flyvetur.',
  },
};